version: ''

services:
  gaart-db:
    container_name: gaart-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - pgdata:var/lib/postgresql/data

volumes:
  pgdata: {}