name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  initialize-server:
    name: Initialize Server
    runs-on: ubuntu-latest
    working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start container
        run: docker-compose -f "docker-compose.yml" up -d


  build-server:
    name: Build
    runs-on: ubuntu-latest
    depends-on: initialize-server
    working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: echo "Testing"


  
    
      